### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by eishiya** [JamesParkNINJA/gbbgtxt#1]
I've found this tool quite useful, but there are a few things about it that make it rather more annoying to use than I'd expect:

- It looks like spaces used for generating the image are added into the original text, which makes it hard to place your cursor at the end of a line. It also has a tendency to mess up line breaks, and editing a text after it's been rendered can cause extra space between lines to appear even in those parts of the text that have not been modified by the user. **Modifications to the string necessary for rendering should not affect the input area at all.**
- The cursor is often automatically placed at the end of the text, making it annoying to make changes to the middle of the text. I suspect fixing the above issue will also fix this one, since I think it happens when the code updates the input, which it should not be doing in the first place.
- There is no way to have both manual line breaks and a line height of 0 (no extra space between lines). I think it would be more intuitive and convenient if line breaks added by the tool were identical to those added manually, and so that setting a line  height of 0 would produce no extra space between lines.
- The number of characters allowed per line seems to be calculated incorrectly. With a max width of 20 tiles and a padding of 0, only 19 characters are allowed on the first line, and only 17 on subsequent lines. With a padding of 1 (therefore an expected line length of 18), it looks like only 17 characters are allowed on line 1, and 15 characters on lines after that...?
![image](https://user-images.githubusercontent.com/70545646/128733043-c8483328-0398-4693-a189-2732ec92bdb8.png)
![image](https://user-images.githubusercontent.com/70545646/128733245-3db11b22-7989-4ef8-aa32-d506d6376d9f.png)

This tool has saved me quite a bit of time, but I think with these issues fixed, it would be even more effective, and largely eliminate the need to edit the results in an image editor afterwards <3

**Comment by JamesParkNINJA** [comment]
- Fixed the manual line-breaks issue

I'm not seeing the max-characters issue (other than the original estimate of it being 19 characters max) however this may be due to the spaces allocated when auto-generating the preview.

Currently working on a way around the spaces being generated, as I remember this was one of the difficulties in the initial build in that I couldn't get it generating correctly without them there.

**Comment by eishiya** [comment]
Unfortunately I can't read jQuery stuff well, so if I were to attempt to fix this, I'd probably end up rewriting everything from scratch ):
(On a related note, why was I assigned this issue? I can try to help if it's needed, but...)

The recent commit seems to have broken all spaces and manual line breaks entirely:
![image](https://user-images.githubusercontent.com/70545646/129595111-246f0ec4-8f3d-4497-a72f-f374397a5928.png)
And increasing line spacing causes the "Y" character to be inserted at the start of each empty line. I'm guessing you're just debugging some stuff on the live version?

**Comment by JamesParkNINJA** [comment]
Ah, sorry, didn't mean to assign you! Haven't touched the old GitHub in a while.

And yeah, it looks like my local is still set up with a link between the two, I'll revert this to my previous change instead, try and make I'm not overwriting it every time.

**Comment by JamesParkNINJA** [comment]
- Fixed max line length issue, where you can only add up to one less than max characters
- Removed need for front-end text input to change to reflect calculated spaces

I still can't replicate the decreasing character lengths, so I can only presume it was partly the autogenerated spaces that may have been affecting this too.

I now have another issue when line-height is above 0, manual linebreaks are double the height they should be so will need to work on this next at Issue #2.

**Comment by JamesParkNINJA** [comment]
Reverting to previous version as current version causes Issue #4

**Comment by JamesParkNINJA** [comment]
Fixed via latest update
