### ISSUE TITLE
No spaces in the generated image

### ISSUE THREAD

**Issue by darkhog** [JamesParkNINJA/gbbgtxt#4]
I put text with spaces in it, but there are no spaces in the resulting image. Firefox stable on Android.

**Comment by JamesParkNINJA** [comment]
Looks like the updates I made for other fixes have broken this. I've reverted back to the original script, but may take a little while for the cache to clear due to my hosting being pretty dire.

**Comment by JamesParkNINJA** [comment]
Fixed via latest update
