### ISSUE TITLE
Padding error + autobreak

### ISSUE THREAD

**Issue by godai78** [JamesParkNINJA/gbbgtxt#5]
*   Looks like the padding and line-height buttons do nothing at all?
*   The line break seems quite arbitrary, sometimes without a reason, the program would break a word into another line even though there is enough room for it to be put in the same line.

I love this tool, looks like this is the only one available online, but I always had to generate the text and move it around by hand in an image editor. I want to make a GB kinetic novel, but if I need to assemble all the story by hand anyway then I think it would be easier to simply generate it on the go.

Any chance the work on this shall be taken up again? Thanks.

**Comment by JamesParkNINJA** [comment]
Fixed via latest update
